import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { ContentLayout } from '@/components/content-layout';
import { pageMetadata } from '@/lib/seo';

export const metadata = pageMetadata('Domain Research Glossary: Counts, Names & Extensions', 'A plain-language guide to the terms used in RegCount: exact matches, related names, extension counts, suffixes, sample data, provider coverage, and CSV exports.', '/glossary');

const terms = [
  { id: 'keyword', term: 'Keyword', group: 'THE INPUT', definition: 'The name you want to research, without an extension. In a RegCount search for cypress.com, the normalized keyword is cypress. Enter the keyword directly if you are starting from a URL with subdomains.', example: 'cypress → the name being compared', link: '/how-it-works', label: 'See the input rules' },
  { id: 'exact-match', term: 'Exact match', group: 'THE MATCH', definition: 'The same complete name appearing under different suffixes. In the interface, cypress.com and cypress.net are examples of the exact name cypress. A longer name such as getcypress is a separate keyword.', example: 'cypress.com + cypress.net → same exact name', link: '/guides/domain-registration-count', label: 'Understand exact-name counts' },
  { id: 'related-name', term: 'Related name', group: 'THE MATCH', definition: 'A different name that contains the searched keyword. Related names can give you ideas for further investigation, but they do not increase the original keyword’s exact-match extension count.', example: 'getcypress → related to cypress, counted separately', link: '/guides/domain-registration-count', label: 'Read about related names' },
  { id: 'extension', term: 'Extension / suffix', group: 'THE RESULT', definition: 'The part shown after the searched name in an extension list. RegCount preserves suffixes supplied by its source, including multi-part forms such as .co.uk. Each distinct suffix appears once in the list.', example: '.com · .net · .co.uk', link: '/guides/domain-extensions-explained', label: 'Explore domain extensions' },
  { id: 'registration-count', term: 'Registration count', group: 'THE RESULT', definition: 'The number of distinct suffixes reported for an exact name by the selected source. It describes breadth within that dataset. It is not the number of visitors, websites, or separate owners behind those domains.', example: 'Read the total together with its source label.', link: '/guides/domain-registration-count', label: 'Learn how to interpret a count' },
  { id: 'extension-category', term: 'Extension category', group: 'THE FILTER', definition: 'A practical grouping used to filter the list. RegCount groups suffixes with a two-character final label as country code and the rest as generic. This simple interface rule is not a complete registry classification.', example: 'Filter first, then inspect the actual suffixes.', link: '/guides/domain-extensions-explained', label: 'Understand the grouping limits' },
  { id: 'coverage', term: 'Provider coverage', group: 'THE SOURCE', definition: 'The names and extensions represented in a data provider’s index. A missing entry can reflect a coverage gap or update timing. It does not by itself confirm that a domain is available to register.', example: 'Not in the index ≠ confirmed available', link: '/how-it-works', label: 'Read the coverage notes' },
  { id: 'sample-data', term: 'Sample data', group: 'THE SOURCE', definition: 'Illustrative names, counts, and suffix lists used to explore the product. RegCount marks them as Sample or Preview in the interface and labels them in CSV exports. They are not verified registration records.', example: 'SAMPLE → an interface example, not a verified fact', link: '/about', label: 'See the project’s current status' },
  { id: 'unknown-result', term: 'Unknown result', group: 'THE RESULT', definition: 'A response without a usable count. The interface may show a dash or a message explaining what happened. A name outside the sample collection is unknown; it is not assigned a confirmed zero.', example: '— → read the row note for context', link: '/how-it-works', label: 'Understand result labels' },
  { id: 'bulk-search', term: 'Bulk search', group: 'THE WORKFLOW', definition: 'Comparing several keywords in one request. RegCount accepts up to 50 input entries, combines normalized duplicates, and lets you sort the returned rows. Select a name to inspect its individual result.', example: 'Shortlist → comparison → individual research', link: '/bulk-domain-search', label: 'Open bulk search' },
  { id: 'csv-export', term: 'CSV export', group: 'THE WORKFLOW', definition: 'A downloadable table for use in a spreadsheet or your research notes. Single-name exports contain domains, extensions, categories, and the source. Bulk exports contain names, counts, source labels, and any row notes.', example: 'Keep the source label alongside the count.', link: '/guides/compare-domain-names', label: 'Build a repeatable comparison' },
];

export default function GlossaryPage() {
  return <ContentLayout label="THE DOMAIN GLOSSARY" title="A common language for your next great name." intro="The terms you’ll encounter in RegCount, explained through the way the product handles names, results, and data sources. Examples explain the concepts; they are not registration claims." breadcrumbs={[{ name: 'Glossary', path: '/glossary' }]}>
    <div className="glossary-layout"><aside className="article-toc"><span>JUMP TO A TERM</span><nav aria-label="Glossary terms">{terms.map(term => <a key={term.id} href={`#${term.id}`}>{term.term}</a>)}</nav></aside><dl className="glossary-list">{terms.map(term => <div id={term.id} key={term.id}><dt><span>{term.group}</span>{term.term}</dt><dd><p>{term.definition}</p><div className="term-example">{term.example}</div><Link href={term.link}>{term.label} <ArrowRight size={14}/></Link></dd></div>)}</dl></div>
  </ContentLayout>;
}
