import Link from 'next/link';
import { ContentLayout } from '@/components/content-layout';
import { pageMetadata } from '@/lib/seo';

export const metadata = pageMetadata('How RegCount Works: Counts, Sources & Coverage', 'See how RegCount handles exact names, distinct suffixes, sample data, provider coverage, bulk searches, CSV exports, and unknown registration counts.', '/how-it-works');
export default function MethodologyPage() {
  return <ContentLayout title="Know what you’re counting." intro="A useful number starts with a clear definition. Here is how RegCount handles names, extensions, and the limits of its data." breadcrumbs={[{ name: 'How it works', path: '/how-it-works' }]}>
    <article className="guide-prose methodology-prose">
      <section><h2>One exact name. Distinct suffixes.</h2><p>RegCount measures the number of distinct extensions reported for an exact name in its source. A name under .com and the same name under .net belong in one exact-name group with two suffixes. Longer names containing the word belong in a separate related-names list.</p><p>Multi-label suffixes remain distinct: .uk and .co.uk can be separate entries. Repeated suffixes are removed from displayed extension lists.</p></section>
      <section><h2>Always read the data label</h2><div className="content-table-wrap" role="region" aria-label="RegCount data labels" tabIndex={0}><table><thead><tr><th scope="col">Label</th><th scope="col">What it means</th></tr></thead><tbody><tr><td>Sample / Preview</td><td>Illustrative names, counts, and extension lists for exploring the interface. These are not verified registration facts.</td></tr><tr><td>dotDB</td><td>A response from the configured registration-data provider. Coverage and freshness depend on that provider’s index.</td></tr><tr><td>No count / —</td><td>No usable count for the row. Read any accompanying message; unknown does not mean zero registrations.</td></tr></tbody></table></div><p>The public preview starts with samples until live data is connected. The live integration uses dotDB’s reported exact-match suffix total and matching extension list. A provider error is shown as an error; it is not replaced with a sample result.</p><p>RegCount is an independent product. Provider attribution identifies the source of a response and does not imply endorsement or ownership.</p></section>
      <section><h2>What you can enter</h2><p>Use a keyword or a registrable domain. The current parser removes a URL wrapper and an initial www label, then compares the first remaining label. cypress, cypress.com, and https://www.cypress.com therefore become the keyword cypress.</p><p>Deeper subdomains are not automatically resolved to the underlying registrable name. Enter cypress directly rather than shop.cypress.com. Internationalized names currently need ASCII/Punycode input. This parser is not a complete public-suffix implementation.</p></section>
      <section><h2>Comparing a list</h2><p><Link href="/bulk-domain-search">Bulk search</Link> accepts up to 50 input entries and combines normalized duplicates. Rows can be sorted by count and exported as CSV. A comparison is most useful when all rows use consistent inputs and the same source.</p><p>Single-name CSV exports include domains, suffixes, categories, and the source. Bulk CSV exports include the keyword, count, source, and any row note. Sample exports keep their illustrative-data label.</p></section>
      <section><h2>Coverage, freshness, and categories</h2><p>A provider-backed result describes a dataset, not a guaranteed census of every registry. Fresh registrations, expiry changes, and coverage gaps can affect what appears. Live responses may be cached by RegCount for up to five minutes; that cache duration is separate from the provider’s own update schedule.</p><p>The country-code filter uses a two-character final-label rule. Other suffixes are grouped as generic. This is a convenient interface grouping, not a complete registry classification. <Link href="/guides/domain-extensions-explained">Read the extension guide</Link> for examples and limitations.</p></section>
      <section><h2>What the tool does not establish</h2><ul><li>A missing extension does not prove that a domain is available to register.</li><li>A registered domain does not necessarily have an active public website.</li><li>An extension count does not identify the number of owners, visitors, or customers.</li><li>A larger count does not establish a sale price or suitability for your project.</li></ul><p>Use the results to organize research, then verify the specific domains and questions that matter to your decision.</p></section>
      <section className="content-callout"><h2>Start with a question, then inspect the details.</h2><p>Our guides explain how to read a count, distinguish suffixes, and build a comparison you can repeat.</p><Link href="/guides">Explore the research guides</Link></section>
    </article>
  </ContentLayout>;
}
